Update to tag 12 and add missing hook file
By installing with a wildcard, we make sure we don't accidentally forget
a hook file in the file listing. As we had...

RPM build errors:
error: Installed (but unpackaged) file(s) found:
   /usr/libexec/updater/10-locale-archive-hook.sh

Signed-off-by: Thiago Macieira <thiago.macieira@intel.com>